using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpoilerToTrackerConverter.SpoilerLog.Enumerators
{
    public enum SortBy
    {
        Default,
        GameSettingsAlphabetic,
        GameSettingsReverseAlphabetic,
        GameSettingsLogOrder,
        JunkLocationsAlphabetic,
        PreCompleteDungeonsAlphabetic,
        PreCompleteDungeonsTrackerOrder,
        EntrancesLong,
        EntrancesShort,
        EntrancesLongAlphabetic,
        EntrancesLongReverseAlphabetic,
        EntrancesShortAlphabetic,
        EntrancesShortReverseAlphabetic,
        EntrancesLongGame,
        EntrancesShortGame,
        EntrancesLongReverseGame,
        EntrancesShortReverseGame,
        TricksAlphabetic,
        TricksReverseAlphabetic,
        TricksDifficulty,
        TricksLogOrder,
        StartingItemsName,
        StartingItemsValue,
        StartingItemsCount,
        GlitchesAlphabetic,
        GlitchesReverseAlphabetic,
        GlitchesDifficulty,
        GlitchesLogOrder,
        WayOfTheHeroHintsWorld,
        WayOfTheHeroHintsLocation,
        WayOfTheHeroHintsItems,
        FoolishHintsWorld,
        FoolishHintsGossip,
        FoolishHintsLocation,
        SpecificHintsWorld,
        SpecificHintsGossip,
        SpecificHintsLocation,
        SpecificHintsItem,
        RegionalHintsWorld,
        RegionalHintsGossip,
        RegionalHintsRegion,
        RegionalHintsItem,
        FoolishRegionsWorld,
        FoolishRegionsRegion,
        FoolishRegionsCount,
        WayOfTheHeroPathsLogOrder,
        WayOfTheHeroPathsWorld,
        WayOfTheHeroPathsDescription,
        WayOfTheHeroPathsPlayer,
        WayOfTheHeroPathsItem,
        PathsPath,
        PathsLocation,
        PathsItem,
        PlandoLocation,
        PlandoItem,
        SpheresWorld,
        SpheresType,
        SpheresNumber,
        SpheresLocation,
        SpheresPlayer,
        SpheresItem,
        LocationsListWorld,
        LocationsListGame,
        LocationsListRegion,
        LocationsListNumber,
        LocationsListCount,
        LocationsListDescription,
        LocationsListPlayer,
        LocationsListItem,
        DungeonRewardsDungeon,
        DungeonRewardsReward,
        DungeonRewardsOrder
    }
}
